version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: erp_calzados_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_erp_calzados
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - erp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: erp_calzados_pma
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - erp-network

volumes:
  mysql_data:

networks:
  erp-network:
    driver: bridge
